package registrarJugadorMVC;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo4
 */
public class PantallaConfigurarJugador extends javax.swing.JFrame implements IPantallaConfigurarJugador {

    /**
     * Creates new form PantallaConfigurarJugador1
     */
    public PantallaConfigurarJugador() {
        initComponents();

        this.setTitle("Rummy - Configurar jugador");

        labelEscojaAvatar.setForeground(Color.WHITE);
        labelIngreseNombre.setForeground(Color.WHITE);
        jPanel1.setBackground(new Color(53, 19, 79, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoImagenes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        avatar8 = new javax.swing.JRadioButton();
        avatar1 = new javax.swing.JRadioButton();
        avatar2 = new javax.swing.JRadioButton();
        avatar3 = new javax.swing.JRadioButton();
        avatar4 = new javax.swing.JRadioButton();
        avatar5 = new javax.swing.JRadioButton();
        avatar6 = new javax.swing.JRadioButton();
        avatar7 = new javax.swing.JRadioButton();
        botonVolver = new componentes.Boton();
        botonConfirmar = new componentes.Boton();
        labelEscojaAvatar = new javax.swing.JLabel();
        labelIngreseNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Jugador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoImagenes.add(avatar8);
        avatar8.setForeground(new java.awt.Color(255, 255, 255));
        avatar8.setText("Avatar 8");
        jPanel1.add(avatar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        grupoImagenes.add(avatar1);
        avatar1.setForeground(new java.awt.Color(255, 255, 255));
        avatar1.setText("Avatar 1");
        jPanel1.add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        grupoImagenes.add(avatar2);
        avatar2.setForeground(new java.awt.Color(255, 255, 255));
        avatar2.setText("Avatar 2");
        jPanel1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        grupoImagenes.add(avatar3);
        avatar3.setForeground(new java.awt.Color(255, 255, 255));
        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        jPanel1.add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        grupoImagenes.add(avatar4);
        avatar4.setForeground(new java.awt.Color(255, 255, 255));
        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon3.png"))); // NOI18N
        jPanel1.add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        grupoImagenes.add(avatar5);
        avatar5.setForeground(new java.awt.Color(255, 255, 255));
        avatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon4.png"))); // NOI18N
        jPanel1.add(avatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        grupoImagenes.add(avatar6);
        avatar6.setForeground(new java.awt.Color(255, 255, 255));
        avatar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon1.png"))); // NOI18N
        jPanel1.add(avatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        grupoImagenes.add(avatar7);
        avatar7.setForeground(new java.awt.Color(255, 255, 255));
        avatar7.setText("Avatar 7");
        jPanel1.add(avatar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        botonVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 5, true));
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.setFocusPainted(false);
        botonVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonVolver.setRadius(50);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 407, 230, 50));

        botonConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 5, true));
        botonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        botonConfirmar.setText("Confirmar");
        botonConfirmar.setFocusPainted(false);
        botonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonConfirmar.setRadius(50);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 407, 230, 50));

        labelEscojaAvatar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        labelEscojaAvatar.setText("Seleccione su avatar");
        jPanel1.add(labelEscojaAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 176, -1, -1));

        labelIngreseNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        labelIngreseNombre.setText("Ingrese su nombre");
        jPanel1.add(labelIngreseNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 50, -1, -1));

        textFieldNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        textFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 91, 536, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 800, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-morado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed

    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        String nombre = textFieldNombre.getText();
        String avatar = "";
        if (!nombre.isBlank()) {
            if (grupoImagenes.getSelection() != null) {
                if (avatar1.isSelected()) {
                    avatar = "awa";
                } else if (avatar2.isSelected()) {
                    avatar = "ewe";
                } else if (avatar3.isSelected()) {
                    avatar = "iwi";
                } else if (avatar4.isSelected()) {
                    avatar = "owo";
                } else if (avatar5.isSelected()) {
                    avatar = "uwu";
                } else if (avatar6.isSelected()) {
                    avatar = "ywy";
                }
                
                if (host) {
                    control.iniciarSeleccionarColores(nombre, avatar);
                } else {
                    control.enviarInformacionAnfitrion(nombre, avatar);
                }
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un avatar.",
                        "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de usuario.",
                    "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonConfirmarActionPerformed

    public static PantallaConfigurarJugador getInstance() {
        if (pantalla == null) {
            pantalla = new PantallaConfigurarJugador();
        }
        return pantalla;
    }

    public void crearParametrosMVC() {
        control = ControlConfigurarJugador.getInstance();
    }

    @Override
    public void update(IModeloConfigurarJugador modelo) {
        
        if (modelo.getError() == null) {
            setVisible(true);
            this.host = modelo.isHost();
        } else {
            JOptionPane.showMessageDialog(this, modelo.getError(),
                    "¡Epa papu!", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avatar1;
    private javax.swing.JRadioButton avatar2;
    private javax.swing.JRadioButton avatar3;
    private javax.swing.JRadioButton avatar4;
    private javax.swing.JRadioButton avatar5;
    private javax.swing.JRadioButton avatar6;
    private javax.swing.JRadioButton avatar7;
    private javax.swing.JRadioButton avatar8;
    private componentes.Boton botonConfirmar;
    private componentes.Boton botonVolver;
    private javax.swing.ButtonGroup grupoImagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEscojaAvatar;
    private javax.swing.JLabel labelIngreseNombre;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
    private static PantallaConfigurarJugador pantalla;
    private ControlConfigurarJugador control;
    private Boolean host;
}
