package registrarJugadorMVC;

import javax.swing.JCheckBox;

/**
 *
 * @author Equipo4
 */
public class PantallaConfigurarJugador extends javax.swing.JFrame implements IPantallaConfigurarJugador{

    /**
     * Creates new form PantallaConfigurarJugador1
     */
    public PantallaConfigurarJugador() {
        initComponents();
        seleccionarAvatar();
        
        this.setTitle("Rummy - Configurar jugador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        avatar4 = new javax.swing.JCheckBox();
        avatar2 = new javax.swing.JCheckBox();
        avatar3 = new javax.swing.JCheckBox();
        avatar5 = new javax.swing.JCheckBox();
        avatar6 = new javax.swing.JCheckBox();
        avatar1 = new javax.swing.JCheckBox();
        avatar7 = new javax.swing.JCheckBox();
        avatar8 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Jugador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        campoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoNombre.setFocusable(false);
        campoNombre.setRequestFocusEnabled(false);
        campoNombre.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 640, 60));

        avatar4.setForeground(new java.awt.Color(255, 255, 255));
        avatar4.setText("Avatar 4");
        getContentPane().add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        avatar2.setForeground(new java.awt.Color(255, 255, 255));
        avatar2.setText("Avatar 2");
        getContentPane().add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        avatar3.setForeground(new java.awt.Color(255, 255, 255));
        avatar3.setText("Avatar 3");
        getContentPane().add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        avatar5.setForeground(new java.awt.Color(255, 255, 255));
        avatar5.setText("Avatar 5");
        getContentPane().add(avatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        avatar6.setForeground(new java.awt.Color(255, 255, 255));
        avatar6.setText("Avatar 6");
        getContentPane().add(avatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        avatar1.setForeground(new java.awt.Color(255, 255, 255));
        avatar1.setText("Avatar 1");
        getContentPane().add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        avatar7.setForeground(new java.awt.Color(255, 255, 255));
        avatar7.setText("Avatar 7");
        getContentPane().add(avatar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        avatar8.setForeground(new java.awt.Color(255, 255, 255));
        avatar8.setText("Avatar 8");
        getContentPane().add(avatar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoDatosJugador.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        setVisible(false);
        String nombre = campoNombre.getText();
        String avatar = getCheckboxSeleccionado().getText();
        control.continuarConfiguracion(nombre, avatar);
    }//GEN-LAST:event_botonConfirmarActionPerformed
    
    private JCheckBox getCheckboxSeleccionado() {
        JCheckBox[] avatars = {avatar1, avatar2, avatar3, avatar4, avatar5, avatar6, avatar7, avatar8};

        for (JCheckBox avatar : avatars) {
            if (avatar.isSelected()) {
                return avatar;
            }
        }
        return avatar1;
    }
    
    private void seleccionarAvatar() {
        JCheckBox[] avatars = {avatar1, avatar2, avatar3, avatar4, avatar5, avatar6, avatar7, avatar8};

        for (JCheckBox avatar : avatars) {
            avatar.addActionListener(e -> {
                for (JCheckBox otro : avatars) {
                    if (otro != avatar) {
                        otro.setSelected(false);
                    }
                }
            });
        }
    }
    
    public static PantallaConfigurarJugador getInstance(){
        if (pantalla == null) {
            pantalla = new PantallaConfigurarJugador();
        }
        return pantalla;
    }
    
    public void crearParametrosMVC(){
        control = ControlConfigurarJugador.getInstance();
    }
    
    @Override
    public void update() {
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox avatar1;
    private javax.swing.JCheckBox avatar2;
    private javax.swing.JCheckBox avatar3;
    private javax.swing.JCheckBox avatar4;
    private javax.swing.JCheckBox avatar5;
    private javax.swing.JCheckBox avatar6;
    private javax.swing.JCheckBox avatar7;
    private javax.swing.JCheckBox avatar8;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private ControlConfigurarJugador control;
    private static PantallaConfigurarJugador pantalla;
    
}
