/*
 * PantallaConfigurarPartida.java
 */
package configurarPartidaMVC;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author Equipo4
 */
public class PantallaConfigurarPartida extends JFrame implements IPantallaConfigurarPartida {

    private ControlConfigurarPartida control;

    /**
     * Creates new form PantallaConfigurarPartida3
     */
    private PantallaConfigurarPartida() {
        initComponents();

        setTitle("Rummy - Configurar Partida");
        jPanel1.setBackground(new Color(53, 19, 79, 255));
        radioButtonDiezFichas.setBackground(new Color(53, 19, 79, 255));
        radioButtonTreceFichas.setBackground(new Color(53, 19, 79, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFichas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        comboBoxNumeroComodines = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioButtonTreceFichas = new javax.swing.JRadioButton();
        radioButtonDiezFichas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        botonCancelar = new componentes.Boton();
        botonCrearPartida = new componentes.Boton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 4, true));

        comboBoxNumeroComodines.setBackground(new java.awt.Color(112, 48, 196));
        comboBoxNumeroComodines.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        comboBoxNumeroComodines.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxNumeroComodines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        comboBoxNumeroComodines.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número de Comodines:");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rango de número de fichas:");

        grupoFichas.add(radioButtonTreceFichas);
        radioButtonTreceFichas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        radioButtonTreceFichas.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonTreceFichas.setText("13 Fichas");
        radioButtonTreceFichas.setFocusPainted(false);

        grupoFichas.add(radioButtonDiezFichas);
        radioButtonDiezFichas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        radioButtonDiezFichas.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonDiezFichas.setText("10 Fichas");
        radioButtonDiezFichas.setFocusPainted(false);
        radioButtonDiezFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDiezFichasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIGURAR PARTIDA");

        botonCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 5, true));
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setFocusPainted(false);
        botonCancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        botonCancelar.setRadius(50);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearPartida.setText("Crear Partida");
        botonCrearPartida.setFocusPainted(false);
        botonCrearPartida.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        botonCrearPartida.setRadius(50);
        botonCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(radioButtonDiezFichas)
                        .addGap(20, 20, 20)
                        .addComponent(radioButtonTreceFichas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(comboBoxNumeroComodines, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(radioButtonDiezFichas)
                    .addComponent(radioButtonTreceFichas))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxNumeroComodines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 760, 350));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-morado.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
        control.cancelarAccion();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void radioButtonDiezFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDiezFichasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonDiezFichasActionPerformed

    private void botonCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPartidaActionPerformed
        if (radioButtonDiezFichas.isSelected() || radioButtonTreceFichas.isSelected()) {
            rangoFichas = 0;

            if (radioButtonDiezFichas.isSelected()) {
                rangoFichas = 10;
            } else if (radioButtonTreceFichas.isSelected()) {
                rangoFichas = 13;
            }

            numeroComodines = Integer.parseInt(comboBoxNumeroComodines.getSelectedItem().toString());
            
            control.verificarPartidaCreada();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el rango de fichas.",
                    "¡Epa, papu!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearPartidaActionPerformed

    public void crearParametrosMVC() {
        control = ControlConfigurarPartida.getInstance();
    }

    @Override
    public void update(IModeloConfigurarPartida modelo) {
        isPartidaCreada = modelo.isPartidaCreada();
        System.out.println(isPartidaCreada);
        if (isPartidaCreada == null) {
            this.setVisible(true);
        } else if (!isPartidaCreada) {
            this.setVisible(false);
            control.crearPartida(rangoFichas, numeroComodines);
        } else {
            setVisible(false);
            JOptionPane.showMessageDialog(this, "Ya existe una partida :(",
                    "¡Epa, papu!", JOptionPane.ERROR_MESSAGE);
            control.cancelarAccion();
        }
    }

    public static PantallaConfigurarPartida getInstance() {
        if (pantalla == null) {
            pantalla = new PantallaConfigurarPartida();
        }
        return pantalla;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Boton botonCancelar;
    private componentes.Boton botonCrearPartida;
    private javax.swing.JComboBox<String> comboBoxNumeroComodines;
    private javax.swing.JLabel fondo;
    private javax.swing.ButtonGroup grupoFichas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioButtonDiezFichas;
    private javax.swing.JRadioButton radioButtonTreceFichas;
    // End of variables declaration//GEN-END:variables
    private Boolean isPartidaCreada;
    private int rangoFichas;
    private int numeroComodines;
    private static PantallaConfigurarPartida pantalla;
}
