/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import java.awt.Color;

/**
 *
 * @author Equipo4
 */
public class FichaComponente extends javax.swing.JPanel {
    private int numero;
    private int color;
    
    /**
     * Constructor de fichaComponente
     * @param numero numero de la ficha
     * @param color color de la ficha
     */
    public FichaComponente(int numero, int color) {
        initComponents();
        this.numero = numero;
        this.color = color;
        
        lblNumero.setText(String.valueOf(numero));
        lblNumero.setForeground(new Color(this.color));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        lblFichaCuerpo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("13");
        lblNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblFichaCuerpo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFichaCuerpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ficha.png"))); // NOI18N
        lblFichaCuerpo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblFichaCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFichaCuerpo;
    private javax.swing.JLabel lblNumero;
    // End of variables declaration//GEN-END:variables
}
