/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.arquitectura.vistas;

import com.mycompany.rummydtos.ConfiguracionPartidaDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import org.itson.arquitectura.controladores.ControlConfigurarPartida;

/**
 *
 * @author Abe
 */
public class PantallaConfigurarPartida extends javax.swing.JDialog {

    private ControlConfigurarPartida control;

    /**
     * Creates new form Inicio
     */
    public PantallaConfigurarPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dibujarComponentes();
        
        control = new ControlConfigurarPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkboxRango13 = new javax.swing.JCheckBox();
        checkboxRango10 = new javax.swing.JCheckBox();
        comboBoxComodines = new javax.swing.JComboBox<>();
        btnVolver = new org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen();
        btnCrearPartida = new org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen();
        btnConfigurar = new org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de comodines de la partida:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 410, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONFIGURACIÓN DE PARTIDA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 520, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rango de número de las fichas:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 360, 40));

        checkboxRango13.setForeground(new java.awt.Color(255, 255, 255));
        checkboxRango13.setText("Holaaa");
        checkboxRango13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxRango13ActionPerformed(evt);
            }
        });
        jPanel1.add(checkboxRango13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 118, 67));

        checkboxRango10.setForeground(new java.awt.Color(255, 255, 255));
        checkboxRango10.setText("Holaaa");
        checkboxRango10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxRango10ActionPerformed(evt);
            }
        });
        jPanel1.add(checkboxRango10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 118, 67));

        comboBoxComodines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel1.add(comboBoxComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 102, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volver.png"))); // NOI18N
        btnVolver.setToolTipText("");
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 262, 52));

        btnCrearPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crearPartida.png"))); // NOI18N
        btnCrearPartida.setToolTipText("");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 262, 52));

        btnConfigurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        jPanel1.add(btnConfigurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 72, 72));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void dibujarComponentes() {
        ImageIcon noSeleccionado = new ImageIcon("src\\main\\resources\\Rectangulo1.png");
        ImageIcon seleccionado = new ImageIcon("src\\main\\resources\\RectanguloSeleccionado1.png");

        ImageIcon noSeleccionado2 = new ImageIcon("src\\main\\resources\\Rectangulo2.png");
        ImageIcon seleccionado2 = new ImageIcon("src\\main\\resources\\RectanguloSeleccionado2.png");

        checkboxRango10.setIcon(noSeleccionado);
        checkboxRango10.setSelectedIcon(seleccionado);
        checkboxRango10.setBorderPainted(false);
        checkboxRango10.setFocusPainted(false);

        checkboxRango13.setIcon(noSeleccionado2);
        checkboxRango13.setSelectedIcon(seleccionado2);
        checkboxRango13.setBorderPainted(false);
        checkboxRango13.setFocusPainted(false);

        checkboxRango10.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkboxRango10.isSelected()) {
                    checkboxRango13.setSelected(false);
                }
            }
        });

        checkboxRango13.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkboxRango13.isSelected()) {
                    checkboxRango10.setSelected(false);
                }
            }
        });

        ImageIcon crearPartida = new ImageIcon("src\\main\\resources\\crearPartida.png");
        ImageIcon crearPartidaSelect = new ImageIcon("src\\main\\resources\\crearPartidaHover.png");

        ImageIcon volver = new ImageIcon("src\\main\\resources\\volver.png");
        ImageIcon volverSelect = new ImageIcon("src\\main\\resources\\volverHover.png");

        btnVolver.setIcon(volver);
        btnVolver.setSelectedIcon(volverSelect);
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);

        btnCrearPartida.setIcon(crearPartida);
        btnCrearPartida.setSelectedIcon(crearPartidaSelect);
        btnCrearPartida.setBorderPainted(false);
        btnCrearPartida.setFocusPainted(false);

        ImageIcon settings = new ImageIcon("src\\main\\resources\\settings.png");
        ImageIcon settingsSelect = new ImageIcon("src\\main\\resources\\settings2.png");

        btnConfigurar.setIcon(settings);
        btnConfigurar.setSelectedIcon(settingsSelect);
        btnConfigurar.setBorderPainted(false);
        btnConfigurar.setFocusPainted(false);
    }

    private void checkboxRango10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRango10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxRango10ActionPerformed

    private void checkboxRango13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRango13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxRango13ActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        ConfiguracionPartidaDTO configuracion = null;
        
        if (checkboxRango10.isSelected()) {
            configuracion = new ConfiguracionPartidaDTO(10, Integer.parseInt(comboBoxComodines.getSelectedItem().toString()));
        } else if (checkboxRango13.isSelected()) {
            configuracion = new ConfiguracionPartidaDTO(10, Integer.parseInt(comboBoxComodines.getSelectedItem().toString()));
        }
        
        control.continuarConfiguracion(configuracion);
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaConfigurarPartida dialog = new PantallaConfigurarPartida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen btnConfigurar;
    private org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen btnCrearPartida;
    private org.itson.arquitectura.configurarpartida.componentesgraficos.BotonConImagen btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkboxRango10;
    private javax.swing.JCheckBox checkboxRango13;
    private javax.swing.JComboBox<String> comboBoxComodines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
