/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.arquitectura.vistas;

/**
 *
 * @author Dell
 */
public class PantallaIntroducirCodigo extends javax.swing.JDialog {

    /**
     * Creates new form PantallaIntroducirCodigo
     */
    public PantallaIntroducirCodigo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAjustes = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1042, 643));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuerca.png"))); // NOI18N
        btnAjustes.setText("jButton11");
        btnAjustes.setBorder(null);
        btnAjustes.setContentAreaFilled(false);
        getContentPane().add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 80));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 540, 50));

        btnVolver.setBackground(new java.awt.Color(100, 0, 143));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 3, true));
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 200, 50));

        btnUnirse.setBackground(new java.awt.Color(100, 0, 143));
        btnUnirse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUnirse.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirse.setText("Unirse");
        btnUnirse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 3, true));
        getContentPane().add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 200, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoIntroducirCodigo.png"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(1042, 643));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaIntroducirCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaIntroducirCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaIntroducirCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaIntroducirCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaIntroducirCodigo dialog = new PantallaIntroducirCodigo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
