/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seleccionColorMVC;

import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class PantallaSeleccionColor extends javax.swing.JDialog {

    private ControlColores controlColores;
    
    /**
     * Creates new form PantallaSeleccionColor
     */
    public PantallaSeleccionColor(java.awt.Frame parent, boolean modal, ControlColores controlColores) {
        super(parent, modal);
        this.controlColores = controlColores;
        initComponents();
        dibujarComponentes();
    }

    public void continuarFlujo(){
        controlColores.continuar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAjustes = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        checkColorNegro = new javax.swing.JCheckBox();
        checkColorAmarillo = new javax.swing.JCheckBox();
        checkColorAzul = new javax.swing.JCheckBox();
        checkColorRojo = new javax.swing.JCheckBox();
        checkColorVerde = new javax.swing.JCheckBox();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuerca.png"))); // NOI18N
        btnAjustes.setText("jButton11");
        btnAjustes.setBorder(null);
        btnAjustes.setContentAreaFilled(false);
        getContentPane().add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 80));

        btnVolver.setBackground(new java.awt.Color(100, 0, 143));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 3, true));
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 200, 50));

        btnConfirmar.setBackground(new java.awt.Color(100, 0, 143));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 3, true));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 200, 50));
        getContentPane().add(checkColorNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));
        getContentPane().add(checkColorAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));
        getContentPane().add(checkColorAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));
        getContentPane().add(checkColorRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));
        getContentPane().add(checkColorVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoSeleccionarColor.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        int[] colores = {0x000000, 0x0014CB, 0xD40000, 0x008309};
        controlColores.agregarColoresJugador(colores);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public void dibujarComponentes(){
        ImageIcon negro = new ImageIcon("src\\main\\resources\\colorNegro.png");
        ImageIcon azul = new ImageIcon("src\\main\\resources\\colorAzul.png");
        ImageIcon rojo = new ImageIcon("src\\main\\resources\\colorRojo.png");
        ImageIcon verde = new ImageIcon("src\\main\\resources\\colorVerde.png");
        ImageIcon amarillo = new ImageIcon("src\\main\\resources\\colorAmarillo.png");
        
        checkColorNegro.setIcon(negro);
        checkColorAzul.setIcon(azul);
        checkColorRojo.setIcon(rojo);
        checkColorVerde.setIcon(verde);
        checkColorAmarillo.setIcon(amarillo);
        
        checkColorNegro.setBorderPainted(false);
        checkColorAzul.setBorderPainted(false);
        checkColorRojo.setBorderPainted(false);
        checkColorVerde.setBorderPainted(false);
        checkColorAmarillo.setBorderPainted(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox checkColorAmarillo;
    private javax.swing.JCheckBox checkColorAzul;
    private javax.swing.JCheckBox checkColorNegro;
    private javax.swing.JCheckBox checkColorRojo;
    private javax.swing.JCheckBox checkColorVerde;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
