/*
 * PantallaInicio.java
 */
package inicioMVC;

import java.awt.Color;

/**
 * Pantalla de inicio del Rummy.
 * 
 * @author Equipo4
 */
public class PantallaInicio extends javax.swing.JFrame implements IPantallaInicio {

    /**
     * Creates new form PantallaInicio2
     */
    private PantallaInicio() {
        initComponents();
        setVisible(true);
        
        this.setTitle("Rummy - Inicio");
        botonUnirsePartida.setBorderColor(new Color(112, 48, 196));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botonUnirsePartida = new componentes.Boton();
        botonCrearPartida = new componentes.Boton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rummy-texto.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        botonUnirsePartida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 3, true));
        botonUnirsePartida.setForeground(new java.awt.Color(255, 255, 255));
        botonUnirsePartida.setText("UNIRSE PARTIDA");
        botonUnirsePartida.setBorderPainted(false);
        botonUnirsePartida.setFocusable(false);
        botonUnirsePartida.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        botonUnirsePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnirsePartidaActionPerformed(evt);
            }
        });
        getContentPane().add(botonUnirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 500, 90));

        botonCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearPartida.setText("CREAR PARTIDA");
        botonCrearPartida.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        botonCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 500, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(112, 48, 196));
        jLabel3.setText("©2024 Equipo 4+1, Inc.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barra-inferior.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cara rummy.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-morado.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonUnirsePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnirsePartidaActionPerformed
        setVisible(false);
        control.unirsePartida();
    }//GEN-LAST:event_botonUnirsePartidaActionPerformed

    private void botonCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPartidaActionPerformed
        setVisible(false);
        control.configurarPartida();
    }//GEN-LAST:event_botonCrearPartidaActionPerformed

    public static PantallaInicio getInstance(){
        if (pantalla == null) {
            pantalla = new PantallaInicio();
        }
        return pantalla;
    }
    
    public void crearParametrosMVC(){
        control = ControlInicio.getInstance();
    }
    
    @Override
    public void update() {
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Boton botonCrearPartida;
    private componentes.Boton botonUnirsePartida;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    private ControlInicio control;
    private static PantallaInicio pantalla;
}
