/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salaEsperaMVC;

import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.itson.arquitecturasoftware.dtorummy.dto.JugadorDTO;

/**
 *
 * @author Equipo4
 */
public class PantallaSalaEspera extends javax.swing.JFrame implements IPantallaSalaEspera {

    private static PantallaSalaEspera instance;
    private ControlSalaEspera control;
    private JugadorDTO jugador; // ERES TÚ PAPU
    private List<JugadorDTO> jugadores;

    /**
     * Creates new form PantallaSalaEspera2
     */
    private PantallaSalaEspera() {
        initComponents();
        
        jPanel1.setBackground(new Color(53, 19, 79, 255));

        lblAvatar2.setVisible(false);
        lblAvatar3.setVisible(false);
        lblAvatar4.setVisible(false);

        lblNombre2.setVisible(false);
        lblNombre3.setVisible(false);
        lblNombre4.setVisible(false);

        lblEstado2.setVisible(false);
        lblEstado3.setVisible(false);
        lblEstado4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListo = new componentes.Boton();
        btnSalir = new componentes.Boton();
        jLabel2 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        lblEstado4 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 48, 196), 4, true));

        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("¡Listo!");
        btnListo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnListo.setRadius(60);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnSalir.setRadius(60);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Esperando jugadores");

        lblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar1.png"))); // NOI18N

        lblNombre1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNombre1.setText("jLabel4");

        lblEstado1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblEstado1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado1.setText("jLabel5");

        lblEstado2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblEstado2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado2.setText("jLabel5");

        lblNombre2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNombre2.setText("jLabel4");

        lblAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar2.png"))); // NOI18N

        lblEstado4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblEstado4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado4.setText("jLabel5");

        lblEstado3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblEstado3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado3.setText("jLabel5");

        lblNombre3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNombre3.setText("jLabel4");

        lblNombre4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNombre4.setText("jLabel4");

        lblAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar5.png"))); // NOI18N

        lblAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAvatar4)
                            .addComponent(lblAvatar3)
                            .addComponent(lblAvatar2)
                            .addComponent(lblAvatar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvatar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvatar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 800, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-morado.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed

    }//GEN-LAST:event_btnListoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Boton btnListo;
    private componentes.Boton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblEstado4;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloSalaEspera modelo) {
        this.setVisible(true);
        jugador = modelo.getJugador();
        if (modelo.getSolicitudUnirse()) {
            int respuesta = JOptionPane.showOptionDialog(
                    null,
                    "Alguien está solicitando unirse a la partida.",
                    "¡Un nuevo jugador ha aparecido!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    new Object[]{"Aceptar", "Rechazar"},
                    "Rechazar"
            );

            boolean aceptado = (respuesta == JOptionPane.YES_OPTION);

            control.evaluarSolicitudUnirse(aceptado);
        }
        jugadores = modelo.getJugadores();
        try {
            llenarDatosJugador(jugadores.get(0), 1);
            llenarDatosJugador(jugadores.get(1), 2);
            llenarDatosJugador(jugadores.get(2), 3);
            llenarDatosJugador(jugadores.get(3), 4);
        } catch (NullPointerException | IndexOutOfBoundsException e) {

        }
    }

    private void llenarDatosJugador(JugadorDTO jugador, int numeroJugador) {
        switch (numeroJugador) {
            case 1:

                lblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource(jugador.getAvatar())));
                lblNombre1.setText(jugador.getNombre());
                lblEstado1.setText(mostrarEstado(jugador));
                break;
            case 2:
                lblAvatar2.setVisible(true);
                lblNombre2.setVisible(true);
                lblEstado2.setVisible(true);

                lblAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource(jugador.getAvatar())));
                lblNombre2.setText(jugador.getNombre());
                lblEstado2.setText(mostrarEstado(jugador));
                break;
            case 3:
                lblAvatar3.setVisible(true);
                lblNombre3.setVisible(true);
                lblEstado3.setVisible(true);

                lblAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource(jugador.getAvatar())));
                lblNombre3.setText(jugador.getNombre());
                lblEstado3.setText(mostrarEstado(jugador));
            case 4:
                lblAvatar4.setVisible(true);
                lblNombre4.setVisible(true);
                lblEstado4.setVisible(true);

                lblAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource(jugador.getAvatar())));
                lblNombre4.setText(jugador.getNombre());
                lblEstado4.setText(mostrarEstado(jugador));
                break;
            default:
                throw new AssertionError();
        }
    }

    public String mostrarEstado(JugadorDTO jugador) {
        if (jugador.isListoParaJugar()) {
            return "¡LISTO!";
        } else {
            return "PENDIENTE...";
        }
    }

    public static PantallaSalaEspera getInstance() {
        if (instance == null) {
            instance = new PantallaSalaEspera();
        }
        return instance;
    }

    public void crearParametrosMVC() {
        control = ControlSalaEspera.getInstance();
    }

}
